[phases.build]
cmds = [
    "apt-get update",
    "apt-get install -y wget gnupg fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 libxss1 libxtst6 xdg-utils chromium",
    "npm install"
]

[start]
cmd = "node index.js"

[variables]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NODE_ENV = "production"
PORT = "3000"

# Desativar healthcheck padr√£o
[healthcheck]
enabled = false
