[phases.setup]
nixPkgs = ["nodejs_18", "chromium"]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "node src/index.js"

[variables]
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NODE_ENV = "production"
PORT = "3000"
